package de.kbgame.geometry;

public enum ImageKey {

	BACKGROUND,
	PERSON,
	BLOCK, BODEN, QUESTION_BLOCK, SPRITE, ENEMY, JUMP_BLOCK,
	QUESTIONBLOCK_BOUNCED_IMAGE,
	BACKGROUND_1, BACKGROUND_2,
	HUD_HEART,
	GOAL
}
